---
title: "siRNAExperiment"
author: "IM"
date: "2023-06-05"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load libraries
library(readr)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggpmisc)
library(lsmeans)
library(ComplexHeatmap)
library(DescTools)
library(stats)
library(svglite)
library(circlize)
library(rlang)
library(patchwork)

#set ligand graphical parameters
my_cols <- c('EGF'='#F68282',
             'IFNG'='#CCB1F1',
             'OSM'='#E6C122'
             )
```

```{r functions, echo=FALSE}
#function to read in phenotypic quantifications from LiveCellPhenotype_Quantification_Figure1.Rmd, perform statistical testing, and construct heatmap
#raw data is available at Zenodo: 10.5281/zenodo.17101147, processed phenotypic data is avilable on github

#read in raw phenotypic data for statistical testing
phenotypic_data_raw<-read_csv('Data/siRNAScreen_Phenotypic_Quantifications_raw.csv')

#scramble normalized data for visualization
phenotypic_data_scr<-read_csv('Data/siRNAScreen_Phenotypic_Quantifications_scr.csv')

phenotype_test<-function(data_raw = phenotypic_data_raw, data_scr = phenotypic_data_scr, phenotype = 'CellCount', phenotypemedian = 'Median_Proliferation'){
  
  #format data
  pheno_dat_full<- data_raw %>%
  filter(siRNA !='WT' & siRNA != 'PLK1' & siRNA !='HIF1A_2') %>%
    select(ligand, siRNA, phenotype, Replicate)
  
  #format scr normalized data for heatmap
  scr_mat<-data_scr %>%
    select(ligand, siRNA, phenotypemedian) %>%
    filter(siRNA != 'SCR') %>%
    spread(key = siRNA, value = phenotypemedian) %>%
    mutate(ligand = factor(ligand, levels = c('EGF', 'OSM', 'IFNG'))) %>%
    column_to_rownames('ligand') %>%
    t %>%
    as.data.frame() %>%
    arrange(desc(OSM)) %>%
    t

  scr_ordered_mat<-scr_mat[c(3,2,1),]
  
  #run ANOVA on phenotypic metrics for each ligand seperately
  formula=reformulate('siRNA', phenotype)
  anova_egf<-aov(formula = formula, data = subset(pheno_dat_full, ligand == 'EGF'))
  anova_osm<-aov(formula = formula, data = subset(pheno_dat_full, ligand == 'OSM'))
  anova_ifng<-aov(formula = formula, data = subset(pheno_dat_full, ligand == 'IFNG'))

  #pairwise t-tests for uncorrected p-values
  pheno_dat_full$siRNA<-factor(pheno_dat_full$siRNA, levels = c('SCR',unique(pheno_dat_full$siRNA)[-10]))

  pair_egf<-pairwise.t.test(x=subset(pheno_dat_full, ligand == 'EGF')[[phenotype]], g=subset(pheno_dat_full, ligand == 'EGF')$siRNA, p.adjust.method = "none")
  pair_osm<-pairwise.t.test(x=subset(pheno_dat_full, ligand == 'OSM')[[phenotype]], g=subset(pheno_dat_full, ligand == 'OSM')$siRNA, p.adjust.method = "none")
  pair_ifng<-pairwise.t.test(x=subset(pheno_dat_full, ligand == 'IFNG')[[phenotype]], g=subset(pheno_dat_full, ligand == 'IFNG')$siRNA, p.adjust.method = "none")

  #format p values for plotting and output
  p_combined<-data.frame(matrix(nrow = 14, ncol = 3))
  colnames(p_combined) <- c('EGF_pvalue',  'IFNG_pvalue', 'OSM_pvalue')
  p_combined$EGF_pvalue<-as.vector((pair_egf[["p.value"]][,1]))
  p_combined$IFNG_pvalue<-as.vector((pair_ifng[["p.value"]][,1]))
  p_combined$OSM_pvalue<-as.vector((pair_osm[["p.value"]][,1]))
  rownames(p_combined)<-rownames(pair_egf[["p.value"]])
  
  #format for heatmap
  p_combined<-p_combined %>%
    t %>%
    as.data.frame() %>%
    select((colnames(scr_ordered_mat)))

  p_combined<-p_combined[c(3,2,1),]

  #heatmap of median proliferation values, with stars for significance
  t<-Heatmap(matrix = scr_ordered_mat,
        name = as.character(phenotype),
        cell_fun = function(j, i, x, y, w, h, fill) {
          if(p_combined[i, j] < 0.001) {
            grid.text("***", x, y, gp = gpar(fontsize = 28))
          } else if(p_combined[i, j] < 0.01) {
            grid.text("**", x, y, gp = gpar(fontsize = 28))
          } else if (p_combined[i, j] < 0.05) {
            grid.text("*", x, y, gp = gpar(fontsize = 28))
          } else{
            grid.text('', x, y)
          }
        },
        show_row_names = T,
        show_column_names = T,
        cluster_columns = F,
        cluster_rows = F,
        na_col = "grey",
        col=colorRamp2(c(.5, 1, 1.5), c("blue", "white", "red")),
        heatmap_legend_param = list(labels_gp = gpar(fontsize = 20),title_gp = gpar(fontsize=20)),
        column_title_gp = gpar(fontsize = 20),
        column_names_gp = gpar(fontsize = 20),
        row_names_gp = gpar(fontsize = 20)) 

  svglite('HM_siRNA.svg',width = 12, height = 8)
  draw(t, heatmap_legend_side = 'right', padding = unit(c(2, 2, 2, 2), "mm"))
  dev.off()
}
```


```{r PCA, echo=FALSE}
#run PCA on combined siRNA phenotype quantification

#format phenotype data for scatterplots
phenotype_dat<-phenotypic_data_scr %>%
  select(ligand, siRNA, Median_Proliferation, Median_msd, Median_neighbors,Median_similarity) %>%
  rename(Median_Motility = Median_msd, Median_Nearest_Neighbor_Distance = Median_neighbors)%>%
  gather(key = 'Phenotypic_Metric', value = 'Phenotype_Score', -siRNA, -ligand) %>%
  spread(key = ligand, value = Phenotype_Score)

#format data for PCA
siRNA_pca<-phenotypic_data_scr %>%
  select(ligand, siRNA, Median_Proliferation, Median_msd, Median_neighbors,Median_similarity) %>%
  rename(Median_Motility = Median_msd, Median_Nearest_Neighbor_Distance = Median_neighbors)%>%
  gather(key = 'Phenotypic_Metric', value = 'Phenotype_Score', -siRNA, -ligand) %>%
  mutate(Pheno_ligand = paste0(ligand,'_', Phenotypic_Metric)) %>%
  filter(siRNA != 'SCR' ) %>%
  select(-ligand, -Phenotypic_Metric) %>%
  spread(key = 'Pheno_ligand', value = 'Phenotype_Score') %>%
  column_to_rownames('siRNA')

#run PCA and extract loadings
pca_res <- prcomp(siRNA_pca, scale. = TRUE)
df <- as.data.frame(pca_res$x)
df$siRNA <- rownames(df)
PCAloadings <- data.frame(Variables = rownames(pca_res$rotation), pca_res$rotation)

#plot PCA
ggplot(df, aes(PC1, PC2)) +
  geom_point(size = 3) +
  geom_text(aes(label = siRNA) , vjust = 2, size = rel(5)) +
  theme_bw() +  
  theme(axis.text.x = element_text(angle = 0, size=rel(2)),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(2)),
        plot.title = element_text(size = rel(2)),legend.text=element_text(size = rel(1)), axis.title = element_text(size = rel(2)),
        legend.title=element_text(size = rel(2)),  panel.grid.minor = element_blank())

# Convert loadings to tidy format
PCAloadings <- data.frame(Variables = rownames(pca_res$rotation), pca_res$rotation)

#average loadings per pc1 and pc2 per phenotype
PCAloadings <- PCAloadings %>%
  mutate(Treatment = sub("_.*", "", Variables)) %>%
  mutate(Phenotype = gsub('.*_', '', Variables))

PCAloadings_avg_posthoc <- PCAloadings %>%
  group_by(Treatment) %>%
  summarise(across(starts_with("PC"), mean))

PCAloadings_avg_posthoc_oth <- PCAloadings %>%
  group_by(Phenotype) %>%
  summarise(across(starts_with("PC"), mean))

p1 <- PCAloadings_avg_posthoc_oth %>%
  ggplot(aes(x = reorder(Phenotype, PC1), y = PC1)) +
  geom_col(fill = "#4F6D7A") +
  coord_flip() +
  xlab("") +
  ylab("Average PC1 Loading (Phenotype)") +
  theme_bw() +
  theme(
    axis.text = element_text(size = rel(1.5)),
    axis.title = element_text(size = rel(2)),
    plot.title = element_text(size = rel(2))
  ) +
  ggtitle("PC1: Phenotype Averages")

p2 <- PCAloadings_avg_posthoc %>%
  ggplot(aes(x = reorder(Treatment, PC1), y = PC1)) +
  geom_col(fill = "#C05746") +
  coord_flip() +
  xlab("") +
  ylab("Average PC1 Loading (Treatment)") +
  theme_bw() +
  theme(axis.text = element_text(size = rel(1.5)),
        axis.title = element_text(size = rel(2)),
        plot.title = element_text(size = rel(2))) +
  ggtitle("PC1: Treatment Averages")

p3 <- PCAloadings %>%
  ggplot(aes(x = Treatment, y = Phenotype, fill = PC1)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  xlab("Treatment") + ylab("Phenotype") +
  theme_bw() +
  theme(axis.text = element_text(size = rel(1.2)),
        axis.title = element_text(size = rel(1.5)),
        plot.title = element_text(size = rel(2))) +
  ggtitle("PC1: Phenotype × Treatment")

# Phenotype averages PC2
p4 <- PCAloadings_avg_posthoc_oth %>%
  ggplot(aes(x = reorder(Phenotype, PC2), y = PC2)) +
  geom_col(fill = "#4F6D7A") +
  coord_flip() +
  xlab("") +
  ylab("Average PC2 Loading (Phenotype)") +
  theme_bw() +
  theme(axis.text = element_text(size = rel(1.5)),
        axis.title = element_text(size = rel(2)),
        plot.title = element_text(size = rel(2))) +
  ggtitle("PC2: Phenotype Averages")

# Treatment averages PC2
p5 <- PCAloadings_avg_posthoc %>%
  ggplot(aes(x = reorder(Treatment, PC2), y = PC2)) +
  geom_col(fill = "#C05746") +
  coord_flip() +
  xlab("") +
  ylab("Average PC2 Loading (Treatment)") +
  theme_bw() +
  theme(axis.text = element_text(size = rel(1.5)),
        axis.title = element_text(size = rel(2)),
        plot.title = element_text(size = rel(2))) +
  ggtitle("PC2: Treatment Averages")

# Detailed matrix PC2
p6 <- PCAloadings %>%
  ggplot(aes(x = Treatment, y = Phenotype, fill = PC2)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  xlab("Treatment") + ylab("Phenotype") +
  theme_bw() +
  theme(axis.text = element_text(size = rel(1.2)),
        axis.title = element_text(size = rel(1.5)),
        plot.title = element_text(size = rel(2))) +
  ggtitle("PC2: Phenotype × Treatment")


final_plot <- (p1 | p2) / p3 | (p4 | p5) / p6 +
  plot_layout(guides = "collect")

```

```{r scatterplots, echo=FALSE}
#plot phenotypic metrics ligand vs ligand in scatterplot
ggplot(subset(phenotype_dat, Phenotypic_Metric == 'Median_Motility'), aes(x=OSM, y=EGF, label = siRNA)) +
  geom_point() + theme_bw()  +geom_text(hjust=0, vjust=0, size=5) + geom_abline(linetype = 'dashed') + coord_fixed() + xlim(c(.5,2)) + ylim(c(.5,2)) + ggtitle("Motility") +
  theme(axis.text.x = element_text(angle = 0, size=rel(2)),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(2)),
        plot.title = element_text(size = rel(2), hjust = .5),legend.text=element_text(size = rel(1)), axis.title = element_text(size = rel(2)),
        legend.title=element_text(size = rel(2)),  panel.grid.minor = element_blank())
```